name: MFDS Daily Monitor

on:
  schedule:
    - cron: '0 0 * * *'  # KST 09:00
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@latest
      with:
        chrome-version: stable
    
    - name: Setup ChromeDriver
      uses: nanasess/setup-chromedriver@v2
    
    - name: Install Python packages
      run: |
        pip install --upgrade pip
        pip install selenium pandas openpyxl
    
    - name: Test Chrome
      run: |
        chrome --version
        chromedriver --version
    
    - name: Run monitoring
      env:
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
      run: |
        python mfds_monitor.py
    
    - name: Check results
      if: always()
      run: |
        echo "Checking for output files..."
        ls -la *.csv 2>/dev/null || echo "No CSV files found"
        ls -la *.xlsx 2>/dev/null || echo "No Excel files found"
    
    - name: Upload data
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: monitor-data-${{ github.run_number }}
        path: |
          previous_data.csv
          *.xlsx
        if-no-files-found: warn
